[package]
name = "purrpass"
version = "0.1.0"
edition = "2021"
license = "AGPL-3"

[workspace]
members = ["crates/config"]


[dependencies]
# Main deps
axum = "0.7"
tokio = { version = "1.36", features = ["macros", "rt", "rt-multi-thread"] }

# Logging
env_logger = "0.11"
log = "0.4"