name: Test and coverage

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: '1.22'

            - name: Test and generate coverage report
              run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: owofied/PurrPass